# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e3249b7f96e71dff9fe3afecc611160584718b383010dc51e4a50278fb58ed7c13f7264cc138f2430b63c41cf5451ec3c748ea8d94f6f717c3307a37aae216

test:
  secret_key_base: b593444078ab1edd517d81f5443f4e535d254eaa271d2360466e4097f682ff3d90090b61691bf4f1e8a95d1df4d8624122dabff6f1224f758c651d2c4bd187f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
